### ISSUE TITLE
Validator container fails after generating json 

### ISSUE THREAD

**Issue by wildmouse** [oasysgames/oasys-private-opstack#26]
I tried instruction on readme, but after [generating json files](https://github.com/oasysgames/oasys-private-opstack?tab=readme-ov-file#generate-genesisjson-and-rollupjson), docker container failed with following error: 

```
panic: invalid argument to Intn
goroutine 96 [running]:
math/rand.(*Rand).Intn(0x400011a150, 0x0)
        math/rand/rand.go:168 +0x98
math/rand.Intn(...)
        math/rand/rand.go:337
github.com/ethereum/go-ethereum/consensus/oasys.(*weightedChooser).random(0x400018ec30)
        github.com/ethereum/go-ethereum/consensus/oasys/scheduler.go:209 +0x70
github.com/ethereum/go-ethereum/consensus/oasys.newScheduler(0x400018e730, 0x28, 0x400018ec30)
        github.com/ethereum/go-ethereum/consensus/oasys/scheduler.go:82 +0x1a8
github.com/ethereum/go-ethereum/consensus/oasys.(*Oasys).scheduler(0x40005b00a0, {0x17c6500, 0x4000181000}, 0x4000642480, 0x400018e730, {0x0, 0x0, 0x0}, {0x0, 0x0, ...})
        github.com/ethereum/go-ethereum/consensus/oasys/oasys.go:1032 +0x28c
github.com/ethereum/go-ethereum/consensus/oasys.(*Oasys).Prepare(0x40005b00a0, {0x17c6500, 0x4000181000}, 0x4000642480)
        github.com/ethereum/go-ethereum/consensus/oasys/oasys.go:534 +0x618
github.com/ethereum/go-ethereum/miner.(*worker).prepareWork(0x4000642900, 0x40007dba40)
        github.com/ethereum/go-ethereum/miner/worker.go:1034 +0x884
github.com/ethereum/go-ethereum/miner.(*worker).commitWork(0x4000642900, 0x4000269008, 0x0, 0x662aed01)
        github.com/ethereum/go-ethereum/miner/worker.go:1121 +0xf8
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0x4000642900)
        github.com/ethereum/go-ethereum/miner/worker.go:529 +0x55c
created by github.com/ethereum/go-ethereum/miner.newWorker
        github.com/ethereum/go-ethereum/miner/worker.go:288 +0x678
```

Below is used repository branch or tags: 

- https://github.com/oasysgames/oasys-private-opstack: main( https://github.com/oasysgames/oasys-private-opstack/commit/386529ec8e2e29f33a6d5da99c2fc122261a0406 ) 
- https://github.com/oasysgames/oasys-validator: `v1.3.0` 
- https://github.com/oasysgames/oasys-opstack: `v1.0.0` 
- https://github.com/oasysgames/oasys-op-geth: main ( https://github.com/oasysgames/oasys-op-geth/commit/389fd30bf5b10bd5dfccaf1d2d5d1f6c72da069f ) 
- https://github.com/oasysgames/opstack-message-relayer: main ( https://github.com/oasysgames/opstack-message-relayer/commit/edc55d1d05b17b6015b1d38cca3a2abfda0beb07 )

**Comment by tak1827** [comment]
I suspect the issue is due to the L1 validator node using the wrong branch. According to [this description](https://github.com/oasysgames/oasys-private-opstack?tab=readme-ov-file#setup-l1-and-op-stack), it should be using the testnet branch.

**Comment by tak1827** [comment]
@wildmouse 
This issue may be caused by not doing join&stake within 40 blocks of starting L1.

**Comment by wildmouse** [comment]
@tak1827 

> I suspect the issue is due to the L1 validator node using the wrong branch. According to [this description](https://github.com/oasysgames/oasys-private-opstack?tab=readme-ov-file#setup-l1-and-op-stack), it should be using the testnet branch.

with `v1.2.0-testnet0` , validator works successfully. 

But another error occured in [next step](https://github.com/oasysgames/oasys-private-opstack?tab=readme-ov-file#generate-genesisjson-and-rollupjson).  

```
docker-compose run --rm --no-deps op-node genesis l2 \
  --deploy-config /op-monorepo/packages/contracts-bedrock/tmp/oasys/L1/build/Build.s.sol/latest/deploy-config.json \
  --l1-deployments /op-monorepo/packages/contracts-bedrock/tmp/oasys/L1/build/Build.s.sol/latest/addresses.json \
  --outfile.l2 /data/genesis.json \
  --outfile.rollup /data/rollup.json \
  --l1-rpc http://l1-rpc:8545/
[+] Building 0.0s (0/0)                                                     docker:desktop-linux
[+] Building 0.0s (0/0)                                                     docker:desktop-linux
t=2024-04-26T05:08:46+0000 lvl=info msg="Deploy config" path=/op-monorepo/packages/contracts-bedrock/tmp/oasys/L1/build/Build.s.sol/latest/deploy-config.json
t=2024-04-26T05:08:46+0000 lvl=crit msg="Application failed" message="cannot unmarshal deploy config: json: unknown field \"messageRelayer\""
```

**Comment by tak1827** [comment]
please use latest version, i've fixed it last week.

**Comment by wildmouse** [comment]
Thank you, now it works, and OP Stack, instant verifier and  Replica Services are running.
